### ISSUE TITLE
Support for eval

### ISSUE THREAD

**Issue by itsmeboy0** [notsapinho/powercord-animated-status#2]
To evaluate javascript expressions, much like in [BetterDiscord-Animated-Status](https://github.com/toluschr/BetterDiscord-Animated-Status).

>### Custom Javascript
>Have the current time as your status:
>```
>"eval let fmt=t=>(t<10?'0':'')+t;let d=new >Date();`${fmt(d.getHours())}:${fmt(d.getMinutes())}:${fmt(d.getSeconds())}`;"
>```
>
>Have the current time with the corresponding clock symbol as your current status
>![Settings Page](https://github.com/toluschr/BetterDiscord-Animated-Status/blob/master/screenshots/status_clock.png?raw=true)
>```
>"eval let fmt=t=>(t<10?'0':'')+t;let d=new >Date();`${fmt(d.getHours())}:${fmt(d.getMinutes())}:${fmt(d.getSeconds())}`;", "eval ['🕛','🕐','🕑','🕒','🕓','🕔','🕕','🕖','🕗','🕘','🕙','🕚'][((new Date()).getHours()%12)];"
>```

**Comment by notsapinho** [comment]
Thanks for the suggestion, it will be implemented in the next update.
